### ISSUE TITLE
User limit issue with non Premium accounts

### ISSUE THREAD

**Issue by ArcadeFighter** [CraftingStore/Suggestions#335] opened 2020-05-13 10:31 UTC
**Describe the bug**
When you have disabled Premuim accounts and set user limit for package, that packages with limits won't go to basket when cracked player want to buy it.

**To Reproduce**
1. Go to 'Packages'
2.  Create package with user limit '1'
3. Go to store where that package
4. To nickname type some non premium account
5. You will see
(You need have to disable Premium accounts)

**Expected behavior**
A package will be added to basket.

**Platform**
CraftingStore website.

**Comment by Tim-NL** [comment] 2020-11-20 21:37
Hi,

Thank you for your report.

The issue was resolved some time ago, I'm not able to reproduce the issue. I did notice that the message about the limit is not shown, so that will be fixed in the coming hour.

-Tim

**Closed by Tim-NL** 2020-11-20 21:37 UTC
