### ISSUE TITLE
More Template Variables

### ISSUE THREAD

**Issue by rohanmcdermott** [CraftingStore/Suggestions#538] opened 2021-03-25 21:17 UTC
(THIS IS NOT ABOUT COMMAND VARIABLES)

CraftingStore is missing quite a few template variables that most competitors have. Here's a list of some variables that would be very useful:
- Global basket variables; basket total, logged in user's username (not just accessible from checkout page)
- Parent Category id for subcategories
- Split the sale price of the package in the 'Featured Package' Module into a separate variable. Currently, it's a single variable.

Additional Features:
- It would also be great to be able to create additional TWIG pages.
- It would also be great to be able to download a whole template for a quick backup.

**Comment by Tim-NL** [comment] 2021-03-25 21:25
Hi,

Please check my reply to the support ticket. As for the variables themselves, this is correct, and not every variable should be accessible globally. That would be inefficient. Because that means we'd have to fetch data from our database that 99% of stores do not use. That is very wasteful. 

I'll close this issue for that reasons; 
- It is by design, variables should not be accessed outside of their scope. Feel free to ask about specific variables in the ticket, some of these are already present.

-Tim

**Closed by Tim-NL** 2021-03-25 21:25 UTC
