### ISSUE TITLE
Package Requirement issue

### ISSUE THREAD

**Issue by didjee2** [CraftingStore/Suggestions#187] opened 2019-04-26 19:09 UTC
**Describe the bug**
For some reason, the **Legendary Rank Upgrade** in our store: https://store.centrixpvp.eu completely ignores the Requirements set to it (Demonic & Demonic Rank Upgrade (either one of them)), while other ranks do not seem to have this issue.

**To Reproduce**
Just go to https://store.centrixpvp.eu, Ranks -> Rank Upgrades & try to buy Legendary Rank Upgrade with a random username (like *qlmjkejmmkljet* (smashing ur keyboard basically))

**Expected behavior**
A message saying that you should have bought at least one of the packages should appear.

**Platform**
CraftingStore Site

**Comment by Tim-NL** [comment] 2019-04-28 11:39
Hello,

Thank you, the feature did work, only the error message did now show up, this has been corrected thanks for the report. 

~Tim

**Comment by didjee2** [comment] 2019-04-28 15:00
![image](https://user-images.githubusercontent.com/12124549/56866179-9aa60480-69d6-11e9-938e-b06e3e2d87f6.png)
I can assure you that that username did not buy the requirements for that rank, but that user **can however go buy that package**.

Tested this on both Firefox (Developer Edition) & Chrome, both allowed me to checkout & go to the payment method while not meeting the package requirements.

These package requirements work for every single package we have in our store **EXCEPT for Legendary Rank Upgrade**.

And yes, the requirements have been setup correctly as far as I know:
![image](https://user-images.githubusercontent.com/12124549/56866221-13a55c00-69d7-11e9-98a8-fb0439e8ef10.png)

**Comment by didjee2** [comment] 2019-04-28 21:15
Seems to happen with other packages aswell now (Titan Rank upgrade is the one I just tested, haven’t checked if the setup was correct though, as I’m on mobile)

**Comment by didjee2** [comment] 2019-07-17 14:52
@Tim-NL this is still an issue ...

**Comment by Tim-NL** [comment] 2019-07-17 14:53
I'm aware, that is why the issue is still open. We will update it when we have more information. 

-Tim

**Comment by didjee2** [comment] 2019-07-17 14:56
Maybe remove the resolved label aswell. This is quite an urgent bug if you ask me so, as Rank Upgrades are straight up impossible when people find out about this bug (which they will).

**Comment by Tim-NL** [comment] 2019-07-17 14:58
Thanks, I did not notice the "resolved" label, we are using another platform that is integrated with GitHub issues to manage them, so we do not lose track of them when this label is present. It was and is still on our bug board. 

-Tim

**Comment by Tim-NL** [comment] 2019-07-18 23:27
We have been debugging for a long time and found out where it went wrong, premium accounts could not order the package, but "cracked" accounts could in some cases. It was not possible to do so on our test packages but it was possible on yours, we implemented a fix for this case and we confirmed it for your store. 

Thanks for the report and sorry for the delay!

-Tim

**Closed by Tim-NL** 2019-07-18 23:27 UTC
