### ISSUE TITLE
SQL Queries do not work

### ISSUE THREAD

**Issue by LostAndDead** [CraftingStore/Suggestions#581] opened 2021-06-20 09:22 UTC
**Describe the bug**
SQL Queries do not send and just sit on pending under the commands tab

**To Reproduce**
1. Setup and SQL Database
2. Create a command to do something (INSERT in my case)
3. Manually purchase the package
4. No data is added to the table

**Expected behavior**
The SQL Query would run as it should

**Platform**
The platform the problem occurred on the CraftingStore website.

**Additional context**
For context this is the query i'm trying to run 
`INSERT INTO Purchases (PlayerUUID, ItemID) VALUES ('88312c47-97a4-455d-badb-bedfdcff842d', 1)`
The uuid value is filled in as it runs it but this is my UUID for the test purchase, when it runs this from a package nothing happens, if i copy the same query into an SQL console it runs and behaves exactly as it should. I have contacted your support about this and after 9 back and forth emails they told me to make a bug report as they cant see anything going wrong and they can connect fine using the credentials therefore its not a login/ip issue.

If you need anymore info just ask, im not in a super rush but it would be nice if this was fixed soon.

**Comment by UncleThaodan** [comment] 2021-06-20 21:47
Are you sure the user you've set in the store has the proper permissions for the database and the table in question?
I can run queries just fine in my store, so I'm not sure it's a bug in the store.

**Comment by LostAndDead** [comment] 2021-06-21 08:19
Yes, as when i log in to test and same with the support assistant we all used the same credentials as the one the store used.

**Comment by UncleThaodan** [comment] 2021-06-22 13:04
I will say that there should be a way of seeing if there were any errors when the command gets executed and if so, the error message as well.
Currently if anything breaks it just stays stuck on "Pending" and "Queued" which is super unhelpful, especially if the command itself is malformed or a different data type is expected.

**Comment by Tim-NL** [comment] 2021-06-28 17:44
Hi,

After checking on one of our test database servers, we confirmed that it does work as expected. So I'm not too sure why it would not work on yours. 

It may be due to the server version, or something else. But nothing that I can reproduce on my end, so I'll be closing this issue here. 

Please try another database server to see if that helps. Sorry.

-Tim

**Closed by Tim-NL** 2021-06-28 17:44 UTC
