### ISSUE TITLE
Crafting store cumulative and sale bugs. 

### ISSUE THREAD

**Issue by AccioAce** [CraftingStore/Suggestions#357] opened 2020-06-02 20:17 UTC
**Describe the bug**
I had cumulative packages enable (Which when someone purchase a rank package it will automatically give them a sale to the next package but I also had a sale on so that double their sale, somehow someone manage to get the next package free without paying) Which it shouldn't have been free.

**To Reproduce**
Package one was $20 and package two was $40 so (If someone purchase package one the you would automatically pay $20 for package two) But along with 50% off it should calculated $10 with the double sale.

**Expected behavior**
I expect the next package to be $10 not for free. From the above description I described and calculated it isn't free.

**Platform**
I am using paper spigot (1.15.2) and latest update of craftingstore.

**Comment by Tim-NL** [comment] 2020-06-21 20:46
Did the user also purchase the first rank with the 50% sale active, or only the second one?

**Comment by AccioAce** [comment] 2020-06-22 05:13
only the second one, the user brought the first rank on the original price.

**Comment by Tim-NL** [comment] 2020-08-10 14:34
We have made modifications to the handling of prices in cumulative packages, could you please validate if the issue is resolved? I'll close the issue for now, you can mention me if it is not resolved for you.

-Tim

**Closed by Tim-NL** 2020-08-10 14:34 UTC
Labels: information needed
