### ISSUE TITLE
Few Serious Issues with the new design

### ISSUE THREAD

**Issue by ghost** [CraftingStore/Suggestions#337] opened 2020-05-17 21:30 UTC
Loving this new design but I am not able to do certain things that kill the functionality of my store.

**Describe the bug**
1. I can't edit certain packages. When editing the package it will show "This has been reported to us." or something like that, or just go straight back to the main page of editing a package. No information is given.

2. Just a tiny bug. When collapsing and showing packages in the package editor https://craftingstore.net/admin/packages
Its pretty buggy sometimes it works sometimes it doesn't

**Expected behavior**

**Screenshots**
https://i.imgur.com/Pb8pKWX.png
Some of the categories have packages 

**Platform**
Website

**Comment by Tim-NL** [comment] 2020-05-17 21:31
Thanks for your reports!

Could you share the pacakge ID with this problem? We saw some errors on package saves, but are not able to reproduce them.

-Tim

**Comment by TaZe-Pug** [comment] 2020-05-18 15:06
338097 is the package id. There's another 4 that also have the same problem.

**Comment by Tim-NL** [comment] 2020-05-18 19:12
Are you still able to cause the error? I'm not able to do so.

**Comment by TaZe-Pug** [comment] 2020-05-19 09:51
Yes. Unfortunately 
https://i.imgur.com/zMipqgd.gifv

**Comment by TaZe-Pug** [comment] 2020-05-19 10:01
Also found out.
This **only** works with packages that were created before the new design. I have created a new package (343405) and replaced the old one (338097) and works perfectly.

**These ones still don't work as they were created before.**
337726
337729
338092

**Comment by Tim-NL** [comment] 2020-05-20 16:20
I cannot reproduce the issues with the package ID's you provided. Did they perhaps have lots of commands?

**Comment by TaZe-Pug** [comment] 2020-05-20 20:53
Nope. They had 0 commands.

**Comment by Tim-NL** [comment] 2020-08-10 13:20
We have not seen this issue pop up since I'll close the issue here. We have made many modifications to system handling this.

-Tim

**Closed by Tim-NL** 2020-08-10 13:20 UTC
